### ISSUE TITLE
Problems generating a correct spec_helper.rb with customisations from .sync.yml

### ISSUE THREAD

**Issue by Odiobill** [puppetlabs/pdk-templates#101]
I wanted to try the simplest possible approach for adding coverage reports to my unit tests. I thought that a rather inelegant but effective approach could be adding some lines to my .sync.yml file and let PDK do the rest:

```yaml
---
.gitlab-ci.yml:
  ovverride: true
  custom:
    ruby_versions:
      '2.4.4':
        puppet_version: "~> 5.5.1"

appveyor.yml:
  delete: true

spec/spec_helper.rb:
  hiera_config: spec/fixtures/hiera/hiera.yaml
  spec_overrides:
    - RSpec.configure do |c|
    -   c.after(:suite) do
    -     RSpec::Puppet::Coverage.report!
    -   end
    - end
    -
```

After running:

```bash
$ pdk convert --template-url <my-pdk-templates-repository-url>
```

The resulting *spec/spec_helper.rb* file contains the content I wanted, but it is missing the "end" statement. You can notice that I inserted and extra empty line: I wanted to see if pdk was just skipping the last entry in the _spec_overrides_, but it turns out that the last "end" is missing anyway:

```yaml
...

# 'spec_overrides' from sync.yml will appear below this line
RSpec.configure do |c|
c.after(:suite) do
RSpec::Puppet::Coverage.report!
end
```
