### ISSUE TITLE
Overriding Appveyor matrix cells instead adds more

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/pdk-templates#132]
I needed to override the default appveyor matrix cells as my module does not support `parallel_spec` testing, only regular `spec`

My .sync.yml has the following snippet:

``` yaml
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests build"
  matrix:
    - RUBY_VERSION: 24-x64
      CHECK: "syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21-x64
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: spec
```

and pdk convert generates the following;

``` yaml
environment:
  matrix:
    -
      RUBY_VERSION: 24-x64
      CHECK: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    -
      PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21-x64
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21
      CHECK: spec
    -
      PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21-x64
      CHECK: spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: spec
```

PDK Template didn't properly see that the override.

Ref: https://github.com/puppetlabs/puppetlabs-dsc

```
  "pdk-version": "1.6.0",
  "template-url": "file://C:/Program Files/Puppet Labs/DevelopmentKit/share/cache/pdk-templates.git",
  "template-ref": "1.6.0-0-gf5564c0"
```
