### ISSUE TITLE
remove ruby2.1.9 from .gitlab-ci

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk-templates#179]
Ruby 2.1.9 is EOL and many gems require ruby 2.2+ now.  As a result of this the gitlab ci that ships with the templates does not work because of gem installation failure due to 2.1.9 ruby version.  Consider changing to 2.4.4 or 2.5.1.

**Comment by rehanone** [comment]
This same problem exists on travis-ci builds as well.

**Comment by TheMeier** [comment]
When doing that its propably advisable to change the rubocop TargetRubyVersion to whatever ```.travis.yml:
  ruby_versions:```
 is at https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.rubocop.yml.erb#L7

**Comment by cdchase** [comment]
I tried unsuccessfully disabling this with the knockout prefix as described here:
https://github.com/puppetlabs/pdk-templates/blob/master/README.md#removing-default-configuration-values

**Comment by natemccurdy** [comment]
If your module still needs Puppet 4 tests in Travis **and** you want to use the latest PDK, the following bit added to your `.sync.yml` will add a Puppet 4 tests that works even with Ruby 2.1.9. The trick is setting a `RUBYGEMS_VERSION` to one that's old enough to support 2.1.9:

```
.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec RUBYGEMS_VERSION=2.7.8
      rvm: 2.1.9
      stage: spec
```
