### ISSUE TITLE
puppet, facter and hiera gems should be configurable

### ISSUE THREAD

**Issue by DavidS** [puppetlabs/pdk-templates#182]
In https://github.com/puppetlabs/pdk-templates/blob/7281db56ead0feeacbc70e5d5dfb3bb885c554ba/moduleroot/Gemfile.erb#L91-L103 we hardcode a bunch of gems that should be configurable through `config_defaults.yaml` instead to allow folks to override with local defaults if necessary.

**Comment by bmjen** [comment]
What use case would this be for? One of the reasons to obfuscate this is so that we can maintain supported configurations via the `puppet-version` option.

**Comment by DavidS** [comment]
```
Gemfile:
  required:
    ':all': # ???
      - gem: puppet
        from_env: PUPPET_GEM_VERSION
```

1. to reduce complexity in the Gemfile.
2. to give folks more rope to shoot themselves in the foot. 


From the timeline of when I wrote that ticket, it must have come up during convergence work with the voxpupuli/modulesync_configs. Apologies for not explaining myself better.
