### ISSUE TITLE
Is it possible to include a gem without the require line?

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#211]
`.sync.yml`

```yaml
Gemfile:
  required:
    ':development':
      - gem: rake
```

output in `Gemfile`

```ruby
gem "rake", require: false
```

output I would like to be able to generate

```ruby
gem "rake"
```
