### ISSUE TITLE
Add ability to add to Rakefile without specifying a bunch of lines in .sync.yml

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#217]
Adding lines to the Rakefile in .sync.yml is not ideal as you must turn readable ruby code that can be parsed and linted into an array of lines in yaml. Instead we should allow users to have a `Rakefile.local`

**Comment by ghoneycutt** [comment]
I'm currently doing this with adding this to a `.sync.yml`

```yaml
Rakefile:
  extras:
    - "if File.readable?('Rakefile.local') then load 'Rakefile.local' end"
```
