### ISSUE TITLE
.travis.yml remove_includes is not well documented

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#225]
It is not clear how to remove the includes.

**Comment by natemccurdy** [comment]
For reference, I had to [figure this out recently](https://github.com/puppetlabs/pdk-templates/pull/178#issuecomment-483937176) and thought I'd share a working example:

```
.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec RUBYGEMS_VERSION=2.7.8
      rvm: 2.1.9
      stage: spec
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
```

To remove an include, you have to list it **exactly** the same as it is seen in `.travis.yml`. All the keys are needed and the key's values must be an exact match.
