### ISSUE TITLE
Need method to allow certain files to be excluded from syntax/lint checks

### ISSUE THREAD

**Issue by salderma** [puppetlabs/pdk-templates#250]
Beaker allows YAML nodeset files to contain ERB template language.  These do not pass the PDK yaml syntax check.  I would like to be able to exclude these files from the syntax checker in a similar fashion to the way rubocop can exclude files.
rubocop example in `.sync.yml`:
```yaml
---
.rubocop.yml:
  default_configs:
    exclude:
      - spec/spec_helper_acceptance.rb
```
