### ISSUE TITLE
Sub Hash in Custom job for gitlab-ci incorrectly converted to string.

### ISSUE THREAD

**Issue by KeithWard** [puppetlabs/pdk-templates#290]
## Describe the Bug
PDK seems to be converting sub hashes inside custom jobs to strings, leading to the inability to specify some keys which require sub-hashes.

Given the following sync.yml:
```yaml
---
.gitlab-ci.yml:                                                                                                        
  override: true                                           
  custom:
    custom_stages:
      - 'unit'
    custom_jobs:
      testjob:
        stage: unit
        image: ruby:2.5.3
        script:
          - 'echo 1'
        artifacts:
          reports:
            junit: 'tmp/*.xml'
```

This results in the following .gitlab-ci.yml job:
```yaml
testjob:
  stage: 'unit'
  image: 'ruby:2.5.3'
  script:
    - testjob
  artifacts:
    reports: '{"junit"=>"tmp/*.xml"}'
```
## Expected Behavior
The job should look like:
```yaml
testjob:
  stage: 'unit'
  image: 'ruby:2.5.3'
  script:
    - testjob
  artifacts:
    reports:
      junit: "tmp/*.xml"
```

## Steps to Reproduce
1. Add sync.yml above
2. run pdk update

## Environment
 - PDK 1.14.1
