### ISSUE TITLE
gettext 3.3.0 gem requires requires Ruby version >= 2.5.0. 

### ISSUE THREAD

**Issue by TheMeier** [puppetlabs/pdk-templates#307]
A new version of gettext gem was released which requires ruby >= 2.5.0. In config_defaults.yml puppet 5 tests are set to ruby 2.4.5  for travis and gitlab.

workaround in .sync.yaml
```yaml
Gemfile:
  required:
    ':development':
      - gem: gettext
        version: '< 3.3.0'
```
