### ISSUE TITLE
Unable to remove ruby-version from .gitlab-ci.yml

### ISSUE THREAD

**Issue by TheMeier** [puppetlabs/pdk-templates#328]
## Describe the Bug
When trying to remove one of the predefined `ruby_versions` for gitlab using knockout prefix template rendering will fail.
example `.sync.yml`

```yaml
---
  
.gitlab-ci.yml:
  override: true
  defaults:
    custom_stages:
      - syntax
      - unit
      - acceptance
    ruby_versions:
      '2.4.5': '---'
      '2.5.7':
        tags:
          - docker
```
This will fail with the following error:
```pdk (FATAL): Failed to render template '.gitlab-ci.yml.erb'
NoMethodError: undefined method `each' for nil:NilClass
pdk (DEBUG): NoMethodError: undefined method `each' for nil:NilClass
pdk (DEBUG): /tmp/pdk-templates20200427-82167-196yg2y/moduleroot/.gitlab-ci.yml.erb:74:in `block in render_erb'
pdk (DEBUG): /tmp/pdk-templates20200427-82167-196yg2y/moduleroot/.gitlab-ci.yml.erb:68:in `each'
pdk (DEBUG): /tmp/pdk-templates20200427-82167-196yg2y/moduleroot/.gitlab-ci.yml.erb:68:in `render_erb'
pdk (DEBUG): /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/2.4.0/erb.rb:896:in `eval'
```

## Expected Behavior
Render .gitlab-ci.yml without error and with only one ruby version

## Steps to Reproduce
See example .sync.yml, simply run pdk update with that on any module.

## Environment
  "pdk-version": "1.17.0",
  "template-url": "https://github.com/puppetlabs/pdk-templates#master",
  "template-ref": "heads/master-0-g4151b0a"

## Additional Context
I suspect https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.gitlab-ci.yml.erb#L5 might be relevant to this

**Comment by benjarrell** [comment]
This configuration will disable the default ruby versions:

```yaml
---
.gitlab-ci.yml:
  override: false
  defaults:
    bundler_args: "--with system_tests --path vendor/bundle --jobs $(nproc)"
    cache:
      paths:
        - "vendor/bundle"
    default_before_script: true
    custom_before_steps:
      - apk add build-base git
    ruby_versions:
      - ---2.5.7
      - ---2.4.5
  custom:
    ruby_versions:
      2.5.8-alpine3.11:
        checks:
          - "syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
          - parallel_spec
        image: "ruby"
        puppet_version: "~> 6.15"
```
