### ISSUE TITLE
support control repo setup

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk-templates#425]
## Use Case
I always convert my control repo to a pdk module using pdk convert.  This gives ability to test and validate with ease on my control repo.

There are some additional configs that I would like to see supported though and was hoping to get some feedback.

## Describe the Solution You Would Like
At a minimum add to config_defaults.yml / sync.yml:

enable_control_repo_support: true # flag to set in .sync.yml

Once enabled
Auto add the following configs:

```
Gemfile:
  required:
    ':development':
      - gem: ra10ke
Rakefile:
  requires:
    - ra10ke
  extras:
    - 'Ra10ke::RakeTask.new'
```

## Describe Alternatives You've Considered
Can always add this to my sync file, but must do every time and with every client
