### ISSUE TITLE
custom gitlab CI steps after the before_script

### ISSUE THREAD

**Issue by skoef** [puppetlabs/pdk-templates#435]
## Use Case
For my gitlab CI jobs to succeed, after bundler installed all modules, I need to run some custom commands to install local gems that I can't install through bundler. Currently the only way to customize the before_script is by defining `custom_before_steps` but those steps will be *prepended* to the default before_script. I need some way to run commands after the default before_script and currently there is no way of hooking into that.

## Describe the Solution You Would Like
The obvious solution would be to add `custom_after_steps` but we need to keep in mind that the `before` in `custom_before_steps` refers to `before_script` and not the fact that the steps run _before_ the before_script rather than _after_. Being able to define custom before_script steps for both being execute before and after the default before_script would solve this. Perhaps these forms could both be allowed for maximum backwards compatibility:

```yaml
custom_before_steps:
  - echo "this is done before the before_script"

custom_before_steps:
  before:
    - echo "this is done before the before_script"
  after:
    - echo "this is done after the before_script"
```

I think this wouldn't be too hard to implement in the template and if agreed I am happy to implement it myself.

## Describe Alternatives You've Considered
Alternatively I would have to define the entire jobs from `ruby_versions` myself and I certainly wouldn't prefer that.
