### ISSUE TITLE
.gitlab-ci.yml should allow tagged docker image names

### ISSUE THREAD

**Issue by silug** [puppetlabs/pdk-templates#447]
## Describe the Bug
https://github.com/puppetlabs/pdk-templates/blob/51828b4067b5e6a85165ad2fefb8d2086e4d5be8/moduleroot/.gitlab-ci.yml.erb#L103 always adds `:`*ruby_version* to the container image name used for tests.  This makes it impossible to use alternative containers (such as vendor-supported ruby containers) that do not have tag names that correspond to ruby versions.

## Expected Behavior
In .sync.yml, I should be able to do something like this:

```yaml
.gitlab-ci.yml:
  custom:
    ruby_versions:
      2.5.7:
        image: registry.redhat.io/rhel8/ruby-25:latest
      2.7.2:
        image: registry.redhat.io/rhel8/ruby-27:latest
```

## Steps to Reproduce
1. Add the previous snipped to .sync.yml
2. `pdk update`
3. You will have an invalid container name (like `registry.redhat.io/rhel8/ruby-25:latest:2.5.7`) in .gitlab-ci.yml.

## Environment
 - PDK Version 2.2.0
 - Platform *any*
