### ISSUE TITLE
YAML anchor in .sync.yml results in bad result

### ISSUE THREAD

**Issue by cdenneen** [puppetlabs/pdk-templates#459]
pdk#main

* .sync.yml
```yaml
.gitlab-ci.yml:
  override: true
  custom:
    image: private.jfrog.io/docker/ap/pdk-docker:latest
    default_before_script: false
    cache:
      paths:
      - /root/.pdk/cache
    global_variables:
      CI_REGISTRY: private.jfrog.io
      PDK_FEATURE_FLAGS: controlrepo
    custom_stages:
    - syntax
    - unit
    - acceptance
    custom_jobs:
      .validate_template: &validate_config
        stage: syntax
        script:
          - pdk validate
        only:
          refs:
          - branches
        except:
          variables:
          - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i

      .spec_template: &spec_config
        stage: unit
        script:
          - pdk test unit --parallel
        only:
          refs:
          - branches
        except:
          variables:
          - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]tests?\]/i

      pdk validate -Puppet ~> 7:
        <<: *validate_config
        variables:
          PDK_PUPPET_VERSION: '7'

      pdk test unit-Puppet ~> 6:
        <<: *spec_config
        variables:
          PDK_PUPPET_VERSION: '6'

      pdk test unit-Puppet ~> 7:
        <<: *spec_config
        variables:
          PDK_PUPPET_VERSION: '7'

```

Results in:

```yaml
---
stages:
  - syntax
  - unit
  - acceptance
variables:
  CI_REGISTRY: 'private.jfrog.io'
  PDK_FEATURE_FLAGS: 'controlrepo'

default:
  image: private.jfrog.io/docker/ap/pdk-docker:latest

  cache:
    paths:
      - /root/.pdk/cache


".validate_template":
  stage: syntax
  script:
  - pdk validate
  only: &1
    refs:
    - branches
  except: &2
    variables:
    - "$CI_COMMIT_MESSAGE =~ /\\[skip[ _-]tests?\\]/i"
".spec_template":
  stage: unit
  script:
  - pdk test unit --parallel
  only: &3
    refs:
    - branches
  except: &4
    variables:
    - "$CI_COMMIT_MESSAGE =~ /\\[skip[ _-]tests?\\]/i"
pdk validate -Puppet ~> 7:
  stage: syntax
  script:
  - pdk validate
  only: *1
  except: *2
  variables:
    PDK_PUPPET_VERSION: '7'
pdk test unit-Puppet ~> 6:
  stage: unit
  script:
  - pdk test unit --parallel
  only: *3
  except: *4
  variables:
    PDK_PUPPET_VERSION: '6'
pdk test unit-Puppet ~> 7:
  stage: unit
  script:
  - pdk test unit --parallel
  only: *3
  except: *4
  variables:
    PDK_PUPPET_VERSION: '7'
```

when it should result in:

```yaml
---
stages:
  - syntax
  - unit
  - acceptance
variables:
  CI_REGISTRY: 'private.jfrog.io'
  PDK_FEATURE_FLAGS: 'controlrepo'

default:
  image: private.jfrog.io/docker/ap/pdk-docker:latest

  cache:
    paths:
      - /root/.pdk/cache


.validate_template: &validate_config
  stage: syntax
  script:
  - pdk validate
  only:
    refs:
    - branches
  except:
    variables:
    - "$CI_COMMIT_MESSAGE =~ /\\[skip[ _-]tests?\\]/i"
.spec_template: &spec_config
  stage: unit
  script:
  - pdk test unit --parallel
  only:
    refs:
    - branches
  except:
    variables:
    - "$CI_COMMIT_MESSAGE =~ /\\[skip[ _-]tests?\\]/i"
pdk validate -Puppet ~> 7:
  <<: *validate_config
  variables:
    PDK_PUPPET_VERSION: '7'
pdk test unit-Puppet ~> 6:
  <<: *spec_config
  variables:
    PDK_PUPPET_VERSION: '6'
pdk test unit-Puppet ~> 7:
  <<: *spec_config
  variables:
    PDK_PUPPET_VERSION: '7'
```

Here is the diff of the result vs the desired result:

```yaml
-".validate_template":
+.validate_template: &validate_config
   stage: syntax
   script:
   - pdk validate
-  only: &1
+  only:
     refs:
     - branches
-  except: &2
+  except:
     variables:
     - "$CI_COMMIT_MESSAGE =~ /\\[skip[ _-]tests?\\]/i"
-".spec_template":
+.spec_template: &spec_config
   stage: unit
   script:
   - pdk test unit --parallel
-  only: &3
+  only:
     refs:
     - branches
-  except: &4
+  except:
     variables:
     - "$CI_COMMIT_MESSAGE =~ /\\[skip[ _-]tests?\\]/i"
 pdk validate -Puppet ~> 7:
-  stage: syntax
-  script:
-  - pdk validate
-  only: *1
-  except: *2
+  <<: *validate_config
   variables:
     PDK_PUPPET_VERSION: '7'
 pdk test unit-Puppet ~> 6:
-  stage: unit
-  script:
-  - pdk test unit --parallel
-  only: *3
-  except: *4
+  <<: *spec_config
   variables:
     PDK_PUPPET_VERSION: '6'
 pdk test unit-Puppet ~> 7:
-  stage: unit
-  script:
-  - pdk test unit --parallel
-  only: *3
-  except: *4
+  <<: *spec_config
   variables:
     PDK_PUPPET_VERSION: '7'
```

The `.gitlab-ci.yml.erb` uses `YAML.dump` for this section which could be causing the issue?

```ruby
<% if configs['custom_jobs'] -%>
<%=  YAML.dump(configs['custom_jobs']).sub(%r{\A---\r?\n}m, '') %>
<% end -%>
```

I've found something similar online about ignoring aliases: https://github.com/yaml/pyyaml/issues/103 but I'm not sure if that's possible here in an ERB template?
