### ISSUE TITLE
GitLab CI is failing due to rubocop-ast dependency under puppet6

### ISSUE THREAD

**Issue by matejzero** [puppetlabs/pdk-templates#475]
## Describe the Bug
CI job for `validate lint check rubocop-Ruby 2.5.7-Puppet ~> 6` is failing due to dependency issue for rubocop-ast.

```
Gem::RuntimeRequirementNotMetError: rubocop-ast requires Ruby version >= 2.6.0.
The current ruby version is 2.5.7.206.
An error occurred while installing rubocop-ast (1.19.1), and Bundler cannot
continue.
Make sure that `gem install rubocop-ast -v '1.19.1' --source
'https://xxxx'` succeeds
before bundling.

In Gemfile:
  puppet-module-posix-dev-r2.5 was resolved to 1.1.1, which depends on
    rubocop-performance was resolved to 1.9.1, which depends on
      rubocop was resolved to 1.6.1, which depends on
        rubocop-ast
```

CI job:
```yaml
validate lint check rubocop-Ruby 2.5.7-Puppet ~> 6:
  stage: syntax
  image: ruby:2.5.7
  script:
    - bundle exec rake validate lint check rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6'
```

## Expected Behavior
CI to successfully run, like it does for puppet 7 checks.

## Steps to Reproduce
Create a new module with pdk new module <name> and push it to GitLab repository for CI to run.

## Environment
 - PDK version 2.5.0
 - Template version 2.5.0
 - Onprem GitLab CI runner
