### ISSUE TITLE
Custom .gitlab-ci.yml settings for litmus not working as expected

### ISSUE THREAD

**Issue by Tamerz** [puppetlabs/pdk-templates#496]
## Describe the Bug
When setting up my .sync to run litmus tests, the default settings get appended to my custom settings, instead of getting replaced. For instance:

```yaml
.gitlab-ci.yml:
  custom:
    use_litmus: true
    litmus:
      provision_list: [rockylinux]
      puppet_collection: [puppet7]
```

This still creates entries in .gitlab-ci.yml for 'centos7' and 'puppet6':

```yaml
litmus-centos-puppet6:
  stage: acceptance
...

litmus-rockylinux-puppet6:
  stage: acceptance
...

litmus-centos-puppet7:
  stage: acceptance
...

litmus-rockylinux-puppet7:
  stage: acceptance
...
```

## Expected Behavior
I would expect it to only create what I specify and nothing else:

```yaml
litmus-rockylinux-puppet7:
  stage: acceptance
...
```

## Steps to Reproduce
* Set `.sync.yml` to the top example.
* Run `pdk update`

## Environment
 - Versions - PDK: 2.6.1, template-url: pdk-default#2.7.1
 - Platform macOS Monterey
