### ISSUE TITLE
Cannot load github_changelog_generator/task

### ISSUE THREAD

**Issue by teluq-pbrideau** [puppetlabs/pdk-templates#513]
## Describe the Bug
Once a brand new module is created, I am not able to run a basic unit test, and receive the following error:

`LoadError: cannot load such file -- github_changelog_generator/task`

## Expected Behavior
I expect the template to be usable at first without thinkering anything

## Steps to Reproduce
1. Create a new module
```
:~/git$ pdk new module examplemodule
```
2. Try to run unit test
```
:~/git/examplemodule$ pdk test unit 
pdk (INFO): Using Ruby 2.7.7
pdk (INFO): Using Puppet 7.24.0
[✖] Preparing to run the unit tests.
[✖] Cleaning up after running unit tests.
pdk (ERROR): The spec_clean rake task failed with the following error(s):

rake aborted!
LoadError: cannot load such file -- github_changelog_generator/task
/home/pbrideau/git/examplemodule/Rakefile:7:in `require'
/home/pbrideau/git/examplemodule/Rakefile:7:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

pdk (FATAL): Failed to clean up after running unit tests
```

## Environment
 -  pdk 2.7.1
 -  Debian 11 (Bullseye)

## Additional Context
I can fix this issue by adding the following to my `.sync.yaml`:
```yaml
---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
```
But I plan to use gitlab for my repo storage, so is that feature really useful to me?  Would it be possible to at least have the option to disable `github_changelog_generator` in `.sync.yaml`?  Or do you recommend me to maintain my own template for this purpose?
