### ISSUE TITLE
Make CI configuration easy to understand (and memorize)

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk-templates#85]
(I'm not sure whether I interpret the content of this repo correctly and reporting here is fine. I apologize if this is plain wrong.)

Migrating a project over to PDK [we've noticed](https://github.com/edestecd/puppet-software/issues/20) that the CI configuration generated by PDK (aka "proposed by Puppet Labs") is somewhat verbose. And not based on commands provided by PDK. Examples:

- [.travis.yml](https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.travis.yml.erb#L20-L29)
- [.gitlab-ci.yml](https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.gitlab-ci.yml.erb#L31-L53)
- [appveyor.yml](https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/appveyor.yml.erb#L24-L36)

I believe one of the strong points of PDK is that it finally provides developers with easy-to-memorize one-shot commands that "do it all", e.g.

- perform linting: `pdk validate`
- run (unit) tests: `pdk test unit`

Hence, it should be obvious that this simplicity can reflect positively on all any CI configuration related to Puppet. It could look like this:

```yaml
- install:
  - apt-get install pdk

- script:
  - pdk validate
  - pdk test unit
```
... or, in a more elaborate setup, using stages (e.g. in Travis):

```yaml
- stage: validate
  script: pdk validate

- stage: test
  script: pdk test unit
```

This is a setup you don't need to look up in documentation to get it explained. It's something you can explain to a colleague even as a complete newbie to CI, Travis & friends.

Can someone explain why the current templates still look, I apologize, confusing and use plain `bundle`, `gem`, `rake` commands?
