### ISSUE TITLE
.sync.yml not working for .gitlab-ci.yml

### ISSUE THREAD

**Issue by Odiobill** [puppetlabs/pdk-templates#89]
Looks like that the instruction provided in the README.md file for changing the content of .gitlab-ci.yml are not correct, or there is a bug. Currently I'm using this content for my .sync.yml:

```yaml
---
.gitlab-ci.yml:
  override: true
  custom:
    ruby_versions:
      '2.4.4':
        'puppet_version': '~> 5.5'

appveyor.yml:
  delete: true
```

The resulting .gitlab-ci.yml:

```yaml
---
stages:
  - test_2.4.1
  - test_2.1.9

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - bundle install --without system_tests

rubocop-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  script:
    - bundle exec rake rubocop

syntax-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  script:
    - bundle exec rake syntax lint

metadata-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  script:
    - bundle exec rake metadata_lint

rspec-puppet-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    CHECK: spec
  script:
    - bundle update
    - bundle exec rake $CHECK

rubocop-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  script:
    - bundle exec rake rubocop

syntax-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  script:
    - bundle exec rake syntax lint

metadata-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  script:
    - bundle exec rake metadata_lint

rspec-puppet-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    CHECK: spec
  script:
    - bundle update
    - bundle exec rake $CHECK
```

Moving "ruby_versions" outside "custom", changes something:

```yaml
---
.gitlab-ci.yml:
  override: true
  ruby_versions:
    '2.4.4':
      puppet_version: "~> 5.5.1"

appveyor.yml:
  delete: true
```

Result:

```yaml
---
stages:
  - test_["2.4.4", {"puppet_version"=>"~> 5.5.1"}]

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - bundle install --without system_tests

rubocop-["2.4.4", {"puppet_version"=>"~> 5.5.1"}]:
  stage: test_["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  image: ruby:["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  script:
    - bundle exec rake rubocop

syntax-["2.4.4", {"puppet_version"=>"~> 5.5.1"}]:
  stage: test_["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  image: ruby:["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  script:
    - bundle exec rake syntax lint

metadata-["2.4.4", {"puppet_version"=>"~> 5.5.1"}]:
  stage: test_["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  image: ruby:["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  script:
    - bundle exec rake metadata_lint

rspec-puppet-["2.4.4", {"puppet_version"=>"~> 5.5.1"}]:
  stage: test_["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  image: ruby:["2.4.4", {"puppet_version"=>"~> 5.5.1"}]
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    CHECK: spec
  script:
    - bundle update
    - bundle exec rake $CHECK
```

Something better is achievable removing the "puppet_version" parameter and using an array instead of a hash for "ruby_versions".

```yaml
---
.gitlab-ci.yml:
  override: true
  ruby_versions:
    - '2.4.4'

appveyor.yml:
  delete: true
```

Still, I would expect to have only the test_2.4.4 stage, while PDK generates everything also for 2.1.9 and 2.4.1:

```yaml
---
stages:
  - test_2.4.1
  - test_2.1.9
  - test_2.4.4

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - bundle install --without system_tests

rubocop-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  script:
    - bundle exec rake rubocop

syntax-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  script:
    - bundle exec rake syntax lint

metadata-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  script:
    - bundle exec rake metadata_lint

rspec-puppet-2.4.1:
  stage: test_2.4.1
  image: ruby:2.4.1
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    CHECK: spec
  script:
    - bundle update
    - bundle exec rake $CHECK

rubocop-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  script:
    - bundle exec rake rubocop

syntax-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  script:
    - bundle exec rake syntax lint

metadata-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  script:
    - bundle exec rake metadata_lint

rspec-puppet-2.1.9:
  stage: test_2.1.9
  image: ruby:2.1.9
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    CHECK: spec
  script:
    - bundle update
    - bundle exec rake $CHECK

rubocop-2.4.4:
  stage: test_2.4.4
  image: ruby:2.4.4
  script:
    - bundle exec rake rubocop

syntax-2.4.4:
  stage: test_2.4.4
  image: ruby:2.4.4
  script:
    - bundle exec rake syntax lint

metadata-2.4.4:
  stage: test_2.4.4
  image: ruby:2.4.4
  script:
    - bundle exec rake metadata_lint

rspec-puppet-2.4.4:
  stage: test_2.4.4
  image: ruby:2.4.4
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    CHECK: spec
  script:
    - bundle update
    - bundle exec rake $CHECK
```
